### ISSUE TITLE
linux support

### ISSUE THREAD

**Issue by mafar** [jden/register-protocol-handler#1]
linux  protocol registration is supported

**Comment by junosuarez** [comment]
Thanks for opening this issue. I would gladly merge a PR adding this feature!

**Comment by mafar** [comment]
Here is the java implementation.
https://github.com/beothorn/URISchemeHandler
https://github.com/beothorn/URISchemeHandler/tree/master/src/main/java/uriSchemeHandler

**Comment by Shubham-Kumar-2000** [comment]
Hi there is a npm module which already supports all major os.

https://www.npmjs.com/package/protocol-registry

You can just use it to add linux and macos support.

I can make a PR if you want

**Comment by junosuarez** [comment]
Thanks for commenting! Unfortunately, I no longer have access to the npm account that owns this package, and due to their ownership policy, I cannot recover it. Thanks for posting an alternative- I'll update the readme here to point to https://www.npmjs.com/package/protocol-registry
